const GOOGLE_OAUTH = "GOOGLE_OAUTH";
const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const FETCH_ALL = "FETCH_ALL";
const FETCH_POST = "FETCH_POST";
const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
const CREATE = "CREATE";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const LIKE = "LIKE";

const START_LOADING = "START_LOADING";
const END_LOADING = "END_LOADING";

export const TYPES = {
  GOOGLE_OAUTH,
  AUTH,
  LOGOUT,
  FETCH_ALL,
  FETCH_POST,
  FETCH_BY_SEARCH,
  CREATE,
  UPDATE,
  DELETE,
  LIKE,
  START_LOADING,
  END_LOADING,
};
